title: Service
icon: folder
files: false
pages: false
options:
  preview: true
  status: true
  template: false
  url: false
  delete: true
fields:
  title:
    label: Título
    type:  text

  text:
    label: Text
    type:  markdown